<?xml version="1.0"?>
<package format="3">
  <name>robot_home_bringup</name>
  <version>0.1.0</version>
  <description>家用机器人系统启动与硬件接口</description>
  <maintainer email="team@robathome.local">Robot Home Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>robot_home_description</depend>
  <depend>robot_state_publisher</depend>
  <depend>joint_state_publisher</depend>
  <exec_depend>driver_bringup</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
